/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/mini_room_art_copy.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, OrthographicCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/mini_room_art_copy.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-450.792, -384.268, 1226.542]}>
          <mesh geometry={nodes.Color_Purple.geometry} material={nodes.Color_Purple.material} position={[292.207, 0, 0]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Color_Yellow.geometry} material={nodes.Color_Yellow.material} position={[-3.761, 0, 0]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Color_Pink.geometry} material={nodes.Color_Pink.material} position={[-292.207, 0, 0]} rotation={[0, -Math.PI / 2, 0]} />
        </group>
        <group position={[546.686, 122.674, -568.112]} rotation={[-0.008, 0.08, -1.568]} scale={[0.74, 1.349, 1.228]}>
          <mesh geometry={nodes.Rectangle.geometry} material={nodes.Rectangle.material} position={[-22.698, 32.77, 1.793]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Cube_4.geometry} material={nodes.Cube_4.material} position={[-0.321, 0.865, 0.42]} rotation={[0.002, 0.001, 0]} scale={[0.994, 1.008, 0.998]} />
          <mesh geometry={nodes.Cube_4_1.geometry} material={nodes.Cube_4_1.material} position={[-16.676, -0.273, 9.748]} rotation={[0.002, 0.001, 0]} scale={[0.994, 1.008, 0.998]} />
        </group>
        <group position={[643.472, 608.805, -737.721]} scale={1.651}>
          <mesh geometry={nodes.Cylinder_4.geometry} material={nodes.Cylinder_4.material} position={[0.247, -107.094, -0.707]} scale={0.854} />
          <mesh geometry={nodes.Cylinder_6.geometry} material={nodes.Cylinder_6.material} position={[-0.155, -65.351, -0.707]} scale={0.854} />
          <mesh geometry={nodes.Cylinder_5.geometry} material={nodes.Cylinder_5.material} position={[-0.155, -149.662, -0.707]} scale={0.854} />
          <mesh geometry={nodes.Cylinder_3.geometry} material={nodes.Cylinder_3.material} position={[-0.532, -212.516, 1.567]} />
          <mesh geometry={nodes.Cylinder_2.geometry} material={nodes.Cylinder_2.material} position={[-0.247, -296.915, 0.707]} />
        </group>
        <group position={[820.649, 713.946, 442.461]}>
          <mesh geometry={nodes.Ellipse_3.geometry} material={nodes.Ellipse_3.material} position={[-2.538, -7.921, 1.445]} rotation={[0, -Math.PI / 2, 0]} scale={0.589} />
          <mesh geometry={nodes.Ellipse_2.geometry} material={nodes.Ellipse_2.material} position={[-2.538, 70.358, 1.445]} rotation={[0, -Math.PI / 2, 0]} scale={0.589} />
          <mesh geometry={nodes.Ellipse.geometry} material={nodes.Ellipse.material} position={[-2.538, 147.533, 1.445]} rotation={[0, -Math.PI / 2, 0]} scale={0.589} />
          <mesh geometry={nodes.Rectangle_5.geometry} material={nodes.Rectangle_5.material} position={[9.477, -26, 0]} rotation={[0, -Math.PI / 2, 0]} />
        </group>
        <group position={[620.145, 554.314, -211.887]} rotation={[0, -Math.PI / 2, 0]} scale={0.707}>
          <mesh geometry={nodes.Triangle_2.geometry} material={nodes.Triangle_2.material} position={[41.469, -49.005, 11.469]} rotation={[0, 0.001, 0]} scale={[1.164, 1.164, 11432065741406.766]} />
          <mesh geometry={nodes.Triangle.geometry} material={nodes.Triangle.material} position={[-100.907, -31.311, 10.859]} rotation={[0, 0.001, 0]} scale={[1.164, 1.164, 11432065741406.766]} />
          <mesh geometry={nodes.Ellipse_1.geometry} material={nodes.Ellipse_1.material} position={[-13.53, 63.176, 9.128]} scale={1.3} />
          <mesh geometry={nodes.Rectangle_6.geometry} material={nodes.Rectangle_6.material} position={[-38.576, 0, -1.015]} scale={0.918} />
          <mesh geometry={nodes.Rectangle_5_1.geometry} material={nodes.Rectangle_5_1.material} position={[-38, 0, -17.875]} />
        </group>
        <group position={[722.772, 745.423, -472.721]} rotation={[0, -Math.PI / 2, 0]} scale={0.621}>
          <mesh geometry={nodes.Ellipse_3_1.geometry} material={nodes.Ellipse_3_1.material} position={[-77.515, 313.592, 4.655]} scale={0.977} />
          <mesh geometry={nodes.Ellipse_2_1.geometry} material={nodes.Ellipse_2_1.material} position={[-127.291, 313.592, 4.655]} scale={0.977} />
          <mesh geometry={nodes.Ellipse_4.geometry} material={nodes.Ellipse_4.material} position={[-178.65, 313.592, 4.655]} scale={0.977} />
          <mesh geometry={nodes.Rectangle_7.geometry} material={nodes.Rectangle_7.material} position={[0, -238.943, 4.003]} />
          <mesh geometry={nodes.Rectangle_9.geometry} material={nodes.Rectangle_9.material} position={[98.234, -16.398, 3.268]} />
          <mesh geometry={nodes.Rectangle_8.geometry} material={nodes.Rectangle_8.material} position={[98.234, 173.681, 3.268]} />
          <mesh geometry={nodes.Rectangle_9_1.geometry} material={nodes.Rectangle_9_1.material} position={[-106.76, -16.398, 3.268]} />
          <mesh geometry={nodes.Rectangle_6_1.geometry} material={nodes.Rectangle_6_1.material} position={[-106.76, 173.681, 3.268]} />
          <mesh geometry={nodes.Rectangle_5_2.geometry} material={nodes.Rectangle_5_2.material} position={[0, 0, -13.469]} />
        </group>
        <group position={[805.649, 559.176, -103.286]} rotation={[0, -Math.PI / 2, 0]} scale={0.656}>
          <group position={[381.081, 121.317, 18.333]} scale={1.006}>
            <mesh geometry={nodes.Cylinder_2_2.geometry} material={nodes.Cylinder_2_2.material} position={[-11.095, 133.571, 0.801]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 1.077, 1]} />
            <mesh geometry={nodes.Cylinder_8.geometry} material={nodes.Cylinder_8.material} position={[-8.64, -133.571, 0.801]} rotation={[0, 0, Math.PI / 2]} scale={[1, 1.077, 1]} />
            <mesh geometry={nodes.Sphere_2.geometry} material={nodes.Sphere_2.material} position={[122.248, 132.867, 0]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.Sphere_1.geometry} material={nodes.Sphere_1.material} position={[-141.8, -132.867, 0]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.Cylinder_2_3.geometry} material={nodes.Cylinder_2_3.material} position={[123.294, 0.972, 0.801]} rotation={[0, 0, Math.PI]} />
            <mesh geometry={nodes.Cylinder_9.geometry} material={nodes.Cylinder_9.material} position={[-142.846, -0.972, 0.801]} />
            <mesh geometry={nodes.Sphere_2_1.geometry} material={nodes.Sphere_2_1.material} position={[122.59, -132.867, 0]} rotation={[0, 0, Math.PI]} />
            <mesh geometry={nodes.Sphere_3.geometry} material={nodes.Sphere_3.material} position={[-142.142, 132.867, 0]} />
          </group>
          <group position={[372.711, 159.533, 22.454]} scale={1.524}>
            <mesh geometry={nodes.A.geometry} material={nodes.A.material} position={[-77, -67.5, 0]} />
            <mesh geometry={nodes.a.geometry} material={nodes.a.material} position={[3.91, -67.5, 0]} />
          </group>
          <mesh geometry={nodes.Rectangle_4.geometry} material={nodes.Rectangle_4.material} position={[369.973, -315.354, 5.684]} scale={1.524} />
          <mesh geometry={nodes.Rectangle_3.geometry} material={nodes.Rectangle_3.material} position={[369.973, -225.14, 5.684]} scale={1.524} />
          <mesh geometry={nodes.Rectangle_2.geometry} material={nodes.Rectangle_2.material} position={[410.365, -135.842, 5.684]} scale={1.524} />
          <mesh geometry={nodes.Rectangle_5_3.geometry} material={nodes.Rectangle_5_3.material} position={[-180.728, -40.121, 19.396]} />
          <mesh geometry={nodes.Rectangle_3_1.geometry} material={nodes.Rectangle_3_1.material} position={[0, -44.003, 5.662]} />
          <mesh geometry={nodes.Rectangle_2_1.geometry} material={nodes.Rectangle_2_1.material} position={[0, 0, -23.619]} />
        </group>
        <group position={[688.693, 174.398, 215.397]}>
          <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} position={[6.442, -6.483, 8.588]} rotation={[0.247, -0.089, -0.251]} />
          <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-10.675, -17.782, -10.371]} rotation={[-0.169, -0.045, 0.258]} />
          <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-3.344, -58.967, 0]} />
        </group>
        <group position={[542.104, 176.093, -121.141]}>
          <mesh geometry={nodes.Cube_4_2.geometry} material={nodes.Cube_4_2.material} position={[120.14, -9.394, -233.331]} />
          <mesh geometry={nodes.Cube_3.geometry} material={nodes.Cube_3.material} position={[120.14, -9.394, 233.306]} />
          <mesh geometry={nodes.Cube_4_3.geometry} material={nodes.Cube_4_3.material} position={[3.727, -4.744, -233.331]} rotation={[0, 0, -1.222]} />
          <mesh geometry={nodes.Cube_2_1.geometry} material={nodes.Cube_2_1.material} position={[3.727, -4.744, 233.306]} rotation={[0, 0, -1.222]} />
          <mesh geometry={nodes.Cube_4_4.geometry} material={nodes.Cube_4_4.material} position={[7.631, -63.454, -233.331]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_1.geometry} material={nodes.Cube_1.material} position={[7.631, -63.454, 233.306]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_2_2.geometry} material={nodes.Rectangle_2_2.material} position={[-3.716, 19.963, 0]} rotation={[-Math.PI / 2, -Math.PI / 9, -Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_1.geometry} material={nodes.Rectangle_1.material} position={[3.42, 0.357, 0]} rotation={[-Math.PI / 2, -Math.PI / 9, -Math.PI / 2]} />
        </group>
        <group position={[-347.786, -106.978, -808.92]}>
          <mesh geometry={nodes.Rectangle_10.geometry} material={nodes.Rectangle_10.material} position={[-0.817, 3.33, 18.218]} rotation={[-0.175, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_5.geometry} material={nodes.Cube_5.material} rotation={[-0.175, 0, 0]} />
        </group>
        <group position={[512.105, -144.893, -840.987]} rotation={[-0.099, 0, 0]} scale={[1.619, 1.615, 0.978]}>
          <mesh geometry={nodes.Rectangle_11.geometry} material={nodes.Rectangle_11.material} position={[-0.561, -0.282, 12.362]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_6.geometry} material={nodes.Cube_6.material} position={[0, 0, -0.362]} />
        </group>
        <group position={[841.128, -199.216, 576.152]} rotation={[-Math.PI / 2, -1.396, -Math.PI / 2]} scale={1.159}>
          <mesh geometry={nodes.Rectangle_12.geometry} material={nodes.Rectangle_12.material} position={[-0.561, -0.282, 12.362]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_7.geometry} material={nodes.Cube_7.material} position={[0, 0, -0.362]} />
        </group>
        <group position={[797.714, -82.051, 719.909]} rotation={[-Math.PI / 2, -1.309, -Math.PI / 2]} scale={1.128}>
          <mesh geometry={nodes.Rectangle_4_1.geometry} material={nodes.Rectangle_4_1.material} position={[-0.945, -1.612, 7.224]} scale={[0.706, 0.937, 0.82]} />
          <mesh geometry={nodes.Rectangle_3_2.geometry} material={nodes.Rectangle_3_2.material} position={[0, 0, -16.177]} scale={[0.706, 0.937, 0.82]} />
          <mesh geometry={nodes.Shape_5.geometry} material={nodes.Shape_5.material} position={[59.992, 8.375, 7.826]} scale={1.152} />
          <mesh geometry={nodes.Shape_4.geometry} material={nodes.Shape_4.material} position={[-157.937, -142.828, 10.164]} scale={1.152} />
          <mesh geometry={nodes.Shape_3.geometry} material={nodes.Shape_3.material} position={[-78.719, 90.444, 17.061]} scale={1.152} />
          <mesh geometry={nodes.Shape_2.geometry} material={nodes.Shape_2.material} position={[-76.813, -2.834, 17.061]} scale={1.152} />
          <mesh geometry={nodes.Shape.geometry} material={nodes.Shape.material} position={[-58.075, 103.381, 14.418]} scale={1.152} />
        </group>
        <group position={[679.367, 709.514, -857.704]} scale={0.517}>
          <mesh geometry={nodes.Rectangle_3_3.geometry} material={nodes.Rectangle_3_3.material} position={[-1.612, 0, -17.527]} />
          <mesh geometry={nodes.Rectangle_13.geometry} material={nodes.Rectangle_13.material} position={[0, 0, 4.265]} />
        </group>
        <group position={[873.939, 539.959, 676.307]} rotation={[0, -Math.PI / 2, 0]} scale={0.62}>
          <mesh geometry={nodes.Rectangle_3_4.geometry} material={nodes.Rectangle_3_4.material} position={[-1.612, 0, -17.527]} />
          <mesh geometry={nodes.Rectangle_14.geometry} material={nodes.Rectangle_14.material} position={[0, 0, 30.303]} />
        </group>
        <group position={[-603.711, 658.285, -849.623]}>
          <mesh geometry={nodes.Ellipse_5.geometry} material={nodes.Ellipse_5.material} position={[37.993, -12.892, 10.735]} rotation={[0, 0, -Math.PI / 2]} scale={0.938} />
          <mesh geometry={nodes.Shape_4_1.geometry} material={nodes.Shape_4_1.material} position={[85.83, -28.037, 8.201]} scale={0.938} />
          <mesh geometry={nodes.Shape_3_1.geometry} material={nodes.Shape_3_1.material} position={[-36.244, 174.262, 8.108]} scale={0.938} />
          <mesh geometry={nodes.Shape_2_1.geometry} material={nodes.Shape_2_1.material} position={[-105.458, 111.353, 7.972]} scale={0.938} />
          <mesh geometry={nodes.Shape_1.geometry} material={nodes.Shape_1.material} position={[-101.045, 111.985, 7.182]} scale={0.938} />
          <mesh geometry={nodes.Rectangle_15.geometry} material={nodes.Rectangle_15.material} position={[0, 0, 2.984]} scale={0.938} />
          <mesh geometry={nodes.Rectangle_3_5.geometry} material={nodes.Rectangle_3_5.material} position={[0, 0, -17.527]} />
        </group>
        <group position={[666.58, 205.463, 370.496]} rotation={[0, -0.175, -0.262]}>
          <mesh geometry={nodes.Shape_3_2.geometry} material={nodes.Shape_3_2.material} position={[-10.484, -28.603, -16.279]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Shape_2_2.geometry} material={nodes.Shape_2_2.material} position={[-10.746, 72.862, -24.099]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Shape_6.geometry} material={nodes.Shape_6.material} position={[-12.404, 52.271, -29.373]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Rectangle_2_3.geometry} material={nodes.Rectangle_2_3.material} position={[-9.93, 0, 0]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Rectangle_3_6.geometry} material={nodes.Rectangle_3_6.material} position={[55.06, -11.51, 7.124]} rotation={[Math.PI / 2, -0.873, Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_16.geometry} material={nodes.Rectangle_16.material} position={[4.404, 0, 0]} rotation={[0, -Math.PI / 2, 0]} />
        </group>
        <group position={[128.996, 617.5, -853.888]}>
          <mesh geometry={nodes.Cube_4_5.geometry} material={nodes.Cube_4_5.material} position={[0.635, 0.937, -10.808]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_5_1.geometry} material={nodes.Cube_5_1.material} position={[1.686, 105.584, 0]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.窗户.geometry} material={nodes.窗户.material} position={[0, 0, 9.159]} rotation={[0, 0, -Math.PI / 2]} />
        </group>
        <group position={[158.538, -140.471, 165.444]}>
          <mesh geometry={nodes.Cube_3_1.geometry} material={nodes.Cube_3_1.material} position={[70.478, -13.2, -67.545]} rotation={[0.086, 0.015, -1.484]} scale={[0.978, 1, 1]} />
          <mesh geometry={nodes.Cube_3_2.geometry} material={nodes.Cube_3_2.material} position={[70.478, -13.2, 68.879]} rotation={[-0.086, -0.015, -1.484]} scale={[0.978, 1, 1]} />
          <mesh geometry={nodes.Cube_2_2.geometry} material={nodes.Cube_2_2.material} position={[-71.758, -13.2, -67.545]} rotation={[0.087, 0, -1.658]} scale={[0.978, 1, 1]} />
          <mesh geometry={nodes.Cube_8.geometry} material={nodes.Cube_8.material} position={[-71.758, -13.2, 68.879]} rotation={[-0.087, 0.008, -1.658]} scale={[0.978, 1, 1]} />
          <mesh geometry={nodes.Cylinder_1.geometry} material={nodes.Cylinder_1.material} position={[0, 152.2, 0]} rotation={[0, -Math.PI / 2, 0]} />
        </group>
        <group position={[478.178, 52.425, 781.078]} rotation={[0, 0.405, 0]} scale={0.752}>
          <mesh geometry={nodes.Cube_2_3.geometry} material={nodes.Cube_2_3.material} position={[15.328, 90.953, -1.224]} rotation={[0, Math.PI / 4, 0]} />
          <mesh geometry={nodes.Cube_3_3.geometry} material={nodes.Cube_3_3.material} position={[-21.328, 13.101, 36.975]} rotation={[-3.054, -Math.PI / 4, -3.054]} scale={1.046} />
          <mesh geometry={nodes.Cube_4_6.geometry} material={nodes.Cube_4_6.material} position={[37.567, -65.585, -107.001]} rotation={[-0.044, 1.223, -0.219]} />
          <mesh geometry={nodes.Cube_5_2.geometry} material={nodes.Cube_5_2.material} position={[-12.894, -31.138, 51.834]} rotation={[-3.113, 1.3, -2.907]} scale={1.046} />
          <mesh geometry={nodes.Cube_9.geometry} material={nodes.Cube_9.material} position={[17.446, -42.096, 91.53]} rotation={[0, -1.222, -0.175]} />
          <mesh geometry={nodes.Ellipse_3_2.geometry} material={nodes.Ellipse_3_2.material} position={[6.874, -137.161, 1.303]} rotation={[-Math.PI / 2, 0, -1.976]} scale={1.543} />
          <mesh geometry={nodes.Plant_Base.geometry} material={nodes.Plant_Base.material} position={[13.953, -371.942, 0.557]} rotation={[-Math.PI / 2, 0, 0]} scale={1.668} />
        </group>
        <group position={[648.155, -183.476, -609.721]} rotation={[0, -0.262, 0]} scale={2.338}>
          <mesh geometry={nodes.Rectangle_2_4.geometry} material={nodes.Rectangle_2_4.material} position={[-10.336, -26.878, 57.125]} />
          <mesh geometry={nodes.Cube_10.geometry} material={nodes.Cube_10.material} position={[-0.693, -0.527, -1.405]} scale={0.776} />
        </group>
        <group position={[-770.834, -194.216, -624.268]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Cube_3_4.geometry} material={nodes.Cube_3_4.material} position={[13.159, -22.511, -7.555]} rotation={[-0.605, 0.045, 2.884]} scale={2.529} />
          <mesh geometry={nodes.Cube_2_4.geometry} material={nodes.Cube_2_4.material} position={[28.142, 5.347, 39.881]} rotation={[0.343, -0.123, 2.814]} scale={2.529} />
          <mesh geometry={nodes.Cube_11.geometry} material={nodes.Cube_11.material} position={[-45.977, -8.653, 19.745]} rotation={[0.014, -0.006, -2.792]} scale={2.529} />
          <mesh geometry={nodes.Ellipse_6.geometry} material={nodes.Ellipse_6.material} position={[-1.56, -20.776, 5.1]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_12.geometry} material={nodes.Cube_12.material} position={[-4.155, -47.238, 4.527]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
        </group>
        <group position={[-473.149, 200.524, -517.548]} rotation={[-0.313, -0.594, -0.132]}>
          <group position={[-2.452, 124.233, 31.488]} rotation={[0.262, 0, 0]}>
            <mesh geometry={nodes.Shape_8.geometry} material={nodes.Shape_8.material} position={[78.909, -222.976, 65.085]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_7.geometry} material={nodes.Shape_7.material} position={[160.245, 193.088, -50.272]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_6_1.geometry} material={nodes.Shape_6_1.material} position={[105.303, 217.945, -51.779]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_5_1.geometry} material={nodes.Shape_5_1.material} position={[-165.44, -26.034, 8.156]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_3_3.geometry} material={nodes.Shape_3_3.material} position={[-164.096, -59.184, 17.481]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_2_3.geometry} material={nodes.Shape_2_3.material} position={[-164.352, -59.806, 18.46]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_9.geometry} material={nodes.Shape_9.material} position={[-163.825, -120.705, 36.171]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Rectangle_2_5.geometry} material={nodes.Rectangle_2_5.material} position={[0, 0, -0.051]} rotation={[-0.262, 0, -Math.PI / 2]} scale={0.946} />
            <mesh geometry={nodes.Rectangle_18.geometry} material={nodes.Rectangle_18.material} position={[0, 0, 0.526]} rotation={[-0.262, 0, -Math.PI / 2]} scale={0.946} />
          </group>
          <mesh geometry={nodes.Cube_5_3.geometry} material={nodes.Cube_5_3.material} position={[-1, 125.367, 14.486]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_6_1.geometry} material={nodes.Cube_6_1.material} position={[2.488, -110.743, -215.131]} rotation={[Math.PI / 6, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_4_7.geometry} material={nodes.Cube_4_7.material} position={[2.488, -180.051, 19.571]} />
          <mesh geometry={nodes.Cube_3_5.geometry} material={nodes.Cube_3_5.material} position={[2.488, 164.407, -19.571]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_2_5.geometry} material={nodes.Cube_2_5.material} position={[118.678, -139.907, -19.571]} rotation={[0, 0, -1.396]} />
          <mesh geometry={nodes.Cube_13.geometry} material={nodes.Cube_13.material} position={[-107.203, -134.706, -19.571]} rotation={[0, 0, -1.745]} />
        </group>
        <group position={[618.829, -107.953, -266.726]} scale={0.702}>
          <mesh geometry={nodes.Cylinder_3_1.geometry} material={nodes.Cylinder_3_1.material} position={[262.369, -38.318, -709.39]} />
          <mesh geometry={nodes.Cylinder_2_1.geometry} material={nodes.Cylinder_2_1.material} position={[262.369, -38.318, 862.796]} />
          <mesh geometry={nodes.Cylinder_3_2.geometry} material={nodes.Cylinder_3_2.material} position={[-249.048, -35.665, -709.39]} />
          <mesh geometry={nodes.Cylinder_7.geometry} material={nodes.Cylinder_7.material} position={[-249.048, -38.318, 862.796]} />
          <mesh geometry={nodes.Rectangle_17.geometry} material={nodes.Rectangle_17.material} position={[0, 230.159, 91.5]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
        </group>
        <group position={[-177.841, -318.388, 98.398]}>
          <mesh geometry={nodes.Ellipse_2_2.geometry} material={nodes.Ellipse_2_2.material} position={[0, 7.389, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.086, 1.086, 1.661]} />
          <mesh geometry={nodes.Ellipse_7.geometry} material={nodes.Ellipse_7.material} position={[0, -7.389, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.086, 1.086, 1.661]} />
        </group>
        <directionalLight intensity={0.7} decay={2} rotation={[1.203, 0.512, -1.385]} target={nodes.Directional_Light.target}>
          <primitive object={nodes.Directional_Light.target} position={[0, 0, -1]} />
        </directionalLight>
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[-3662.89, 2379.989, 3678.248]} rotation={[-0.539, -0.715, -0.374]} />
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[-4181.331, 3140.372, 2345.382]} rotation={[-0.898, -0.842, -0.752]} />
        <mesh geometry={nodes.Walls.geometry} material={nodes.Walls.material} position={[33.168, -323.764, -23.547]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.702} />
        <mesh geometry={nodes['heart-ui'].geometry} material={nodes['heart-ui'].material} position={[750.976, 324.971, 495.205]} rotation={[-0.59, -1.362, -1.13]} />
        <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[153.76, -206.693, -725.749]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes['book-green'].geometry} material={nodes['book-green'].material} position={[797.817, 181.701, -733.6]} rotation={[-Math.PI / 2, -1.396, -Math.PI / 2]} />
        <mesh geometry={nodes['book-red'].geometry} material={nodes['book-red'].material} position={[873.039, 235.865, -716.946]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['book-yellow'].geometry} material={nodes['book-yellow'].material} position={[850.549, 201.365, -716.946]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.paper.geometry} material={nodes.paper.material} position={[490.666, 107.272, -605.117]} rotation={[-Math.PI / 2, 0, -1.134]} />
      </group>
    </group>
  )
}

useGLTF.preload('/mini_room_art_copy.gltf')
