/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 beanBag.gltf 
Author: Blerim Arifi (https://sketchfab.com/Blerim_Arifi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/velvet-bean-bag-bee48f52ffe5407fab1f0f8b206f4424
Title: Velvet Bean Bag
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function BeanBag(props) {
  const { nodes, materials } = useGLTF('/beanBag.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Color} position={[0.075, 1.928, -0.043]} />
    </group>
  )
}

useGLTF.preload('/beanBag.gltf')

export default BeanBag;