/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 bookShelf.gltf 
Author: 3D_for_everyone (https://sketchfab.com/boglarka4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/metal-frame-bookcase-02e035d1a09943c2ac62163115239278
Title: Metal frame bookcase
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function BookShelf(props) {
  const { nodes, materials } = useGLTF('/bookShelf.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[23.698, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <group position={[0.863, 0, 2.467]}>
              <mesh geometry={nodes.Vase_2_Vase_2_0.geometry} material={materials.Vase_2} />
              <mesh geometry={nodes.Plant_3_Plant001_0.geometry} material={materials['Plant.001']} position={[-0.018, -0.005, 0.032]} rotation={[-1.791, -0.63, 1.551]} scale={0.325} />
            </group>
            <group position={[0.863, 0, 2.021]}>
              <mesh geometry={nodes.Vase_3_Vase_3_0.geometry} material={materials.Vase_3} />
              <mesh geometry={nodes.Swiss_cheese_plant_3_Swiss_cheese_plant_2001_0.geometry} material={materials['Swiss_cheese_plant_2.001']} position={[-0.066, -0.128, 0.204]} rotation={[-2.025, -0.909, 1.66]} scale={0.256} />
              <mesh geometry={nodes.Swiss_cheese_plant_2_Swiss_cheese_plant_2001_0.geometry} material={materials['Swiss_cheese_plant_2.001']} position={[0.107, 0.006, 0.171]} rotation={[1.765, 0.01, -1.117]} scale={0.156} />
              <mesh geometry={nodes.Swiss_cheese_plant_1_Swiss_cheese_plant_1001_0.geometry} material={materials['Swiss_cheese_plant_1.001']} position={[-0.037, 0.163, 0.133]} rotation={[-0.262, 1.23, 0.453]} scale={0.241} />
            </group>
            <group position={[-0.526, 0, 2.492]}>
              <mesh geometry={nodes.Vase_1_Vase_1_0.geometry} material={materials['Vase_1.']} />
              <mesh geometry={nodes.Plant_1_Plant_1_0.geometry} material={materials.Plant_1} position={[0.004, 0.002, 0.044]} rotation={[1.415, -0.649, -1.02]} scale={[0.221, 0.252, 0.206]} />
            </group>
            <group position={[-0.525, 0, 1.045]}>
              <mesh geometry={nodes.Cup_podium_Couch_metal_0.geometry} material={materials.Couch_metal} />
              <mesh geometry={nodes.Cup_Cup_0.geometry} material={materials.material} position={[0, 0, 0.263]} scale={1.02} />
            </group>
            <group position={[-0.087, 0.237, 1.923]} rotation={[Math.PI / 2, 0.09, 0]} scale={[1.61, 2.111, 1.48]}>
              <group position={[-0.093, 0.029, 0.073]} rotation={[0, 1.26, 0]} scale={[0.855, 0.604, 0.798]}>
                <mesh geometry={nodes.Book_3002_Book_3001_0.geometry} material={materials['Book_3.001']} />
                <mesh geometry={nodes.Book_3002_Book_3_paper001_0.geometry} material={materials['Book_3_paper.001']} />
              </group>
              <mesh geometry={nodes.Book_9_Book_9001_0.geometry} material={materials['Book_9.001']} />
              <mesh geometry={nodes.Book_9_Book_9_paper001_0.geometry} material={materials['Book_9_paper.001']} />
              <mesh geometry={nodes.Golden_Deer_1_Gold_0.geometry} material={materials.Gold} position={[-0.008, 0.044, 0.105]} rotation={[-1.608, 0.023, 0.683]} scale={[0.136, 0.138, 0.1]} />
            </group>
            <group position={[-0.573, 0.191, 0.521]} rotation={[Math.PI / 2, 1.108, 0]} scale={1.231}>
              <group position={[-0.047, 0.059, -0.004]} scale={1.046}>
                <mesh geometry={nodes.Book_4_Book_4001_0.geometry} material={materials['Book_4.001']} />
                <mesh geometry={nodes.Book_4_Book_4_paper001_0.geometry} material={materials['Book_4_paper.001']} />
              </group>
              <group position={[-0.028, 0.04, 0.021]} rotation={[0, 0.16, 0]} scale={0.951}>
                <mesh geometry={nodes.Book_5_Book_5001_0.geometry} material={materials['Book_5.001']} />
                <mesh geometry={nodes.Book_5_Book_5_paper002_0.geometry} material={materials['Book_5_paper.002']} />
              </group>
              <mesh geometry={nodes.Book_11_Book_11001_0.geometry} material={materials['Book_11.001']} />
              <mesh geometry={nodes.Book_11_Book_11_paper001_0.geometry} material={materials['Book_11_paper.001']} />
              <mesh geometry={nodes.Candle_holder_Gold_0.geometry} material={materials.Gold} position={[-0.068, 0.088, 0.113]} rotation={[-Math.PI / 2, 0, -1.108]} scale={0.05} />
            </group>
            <group position={[0.756, 0.226, 0.106]} rotation={[Math.PI / 2, 0.127, -0.515]} scale={[1.42, 1.862, 1.305]}>
              <group position={[-0.092, -0.065, 0.023]} rotation={[0, 0, 0.521]} scale={[0.634, 0.553, 0.728]}>
                <mesh geometry={nodes.Book_1002_Book_1001_0.geometry} material={materials['Book_1.001']} />
                <mesh geometry={nodes.Book_1002_Book_1_paper002_0.geometry} material={materials['Book_1_paper.002']} />
              </group>
              <group position={[-0.091, -0.038, 0.035]} rotation={[0, 0, 0.521]} scale={[0.685, 0.597, 0.786]}>
                <mesh geometry={nodes.Book_2002_Book_2001_0.geometry} material={materials['Book_2.001']} />
                <mesh geometry={nodes.Book_2002_Book_2_paper001_0.geometry} material={materials['Book_2_paper.001']} />
              </group>
              <group position={[0.16, 0.051, 0.031]} rotation={[0.055, -0.118, 0.524]} scale={[0.69, 0.785, 0.789]}>
                <mesh geometry={nodes.Book_8_Book_8001_0.geometry} material={materials['Book_8.001']} />
                <mesh geometry={nodes.Book_8_Book_8_paper002_0.geometry} material={materials['Book_8_paper.002']} />
              </group>
              <mesh geometry={nodes.Book_13_Book_13001_0.geometry} material={materials['Book_13.001']} />
              <mesh geometry={nodes.Book_13_Book_13_paper001_0.geometry} material={materials['Book_13_paper.001']} />
            </group>
            <group position={[0.203, 0.071, 1.429]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.345}>
              <mesh geometry={nodes.Book_pack_8_Book_pack_8001_0.geometry} material={materials['Book_pack_8.001']} />
              <mesh geometry={nodes.Book_pack_8_Book_pack_8_paper001_0.geometry} material={materials['Book_pack_8_paper.001']} />
            </group>
            <group position={[0.588, 0.136, 1.554]} rotation={[-1.317, 0.125, 3.109]} scale={0.091}>
              <mesh geometry={nodes.Picture_frame_1_Picture_farme_0.geometry} material={materials.Picture_farme} />
              <mesh geometry={nodes.Picture_frame_1_Picture_1_0.geometry} material={materials.Picture_1} />
            </group>
            <group position={[0.803, -0.011, 1.577]} rotation={[-1.306, -0.312, -3.059]} scale={0.107}>
              <mesh geometry={nodes.Picture_frame_2_Picture_farme_0.geometry} material={materials.Picture_farme} />
              <mesh geometry={nodes.Picture_frame_2_Picture_2_0.geometry} material={materials.Picture_2} />
            </group>
            <mesh geometry={nodes.Shelf_frame_Couch_metal_0.geometry} material={materials.Couch_metal} />
            <mesh geometry={nodes.Shelf_cube_4_Cabinet_wood_0.geometry} material={materials.Cabinet_wood} position={[-0.514, 0, 0.245]} />
            <mesh geometry={nodes.Shelf_cube_2_Cabinet_wood_0.geometry} material={materials.Cabinet_wood} position={[0.863, 0, 2.114]} />
            <mesh geometry={nodes.Shelf_cube_3_Cabinet_wood_0.geometry} material={materials.Cabinet_wood} position={[-0.514, 0, 1.409]} />
            <mesh geometry={nodes.Shelf_cube_1_Drawer_wood_0.geometry} material={materials.Drawer_wood} position={[-0.514, 0, 2.574]} />
            <mesh geometry={nodes.Shelf_cube_5_Cabinet_wood_0.geometry} material={materials.Cabinet_wood} position={[0.863, 0, 0.597]} />
            <mesh geometry={nodes.Golden_Deer_2_Gold_0.geometry} material={materials.Gold} position={[0.218, 0.095, 0.06]} rotation={[0, 0, -0.636]} scale={0.177} />
            <mesh geometry={nodes.Plant_4_Plant_2_0.geometry} material={materials.Plant_2} position={[0.858, -0.014, 0.729]} rotation={[-1.669, -1.303, 1.634]} scale={0.598} />
            <mesh geometry={nodes.Gear_Gear_0.geometry} material={materials.Gear} position={[0.324, 0.041, 2.547]} rotation={[0, 0, 0.458]} scale={1.183} />
            <mesh geometry={nodes.Gear001_Gear_0.geometry} material={materials.Gear} position={[0.416, 0.137, 2.459]} rotation={[0, 0, -Math.PI]} scale={0.614} />
            <mesh geometry={nodes.Shelf_1_Cabinet_wood001_0.geometry} material={materials['Cabinet_wood.001']} position={[0.237, 0, 1.413]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bookShelf.gltf')

export default BookShelf;
