/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 clock.gltf 
Author: Nick Kotik (https://sketchfab.com/Nathanson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-clock-29a3f59a59204285b745f8acc8e09a19
Title: Modern Clock
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

function Clock(props) {
  const group = React.useRef()
  const { scene } = useGLTF('/clock.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials, animations } = useGraph(clone)
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Wall_1" position={[0.033, 0.067, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Wall} />
              </group>
              <group name="Cylinder_2" position={[0, 0.005, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.007, 0.018, 0.007]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Metal} />
              </group>
              <group name="Arrow1_3" position={[-0.003, 0.005, 0]} rotation={[-0.472, 0, -Math.PI / 2]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Metal} />
              </group>
              <group name="Clock_4" position={[0, -0.026, -0.032]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Wood_texture} />
              </group>
              <group name="Arrow2_5" position={[0.001, 0.005, 0]} rotation={[-2.581, 0, -Math.PI / 2]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Metal} />
              </group>
              <group name="Neon_6" position={[-0.034, 0.005, 0]} rotation={[0, 0, Math.PI / 2]} scale={[1.33, 0.953, 1.33]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Emis} />
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Material} />
              </group>
              <group name="Armature_9" position={[-0.018, 0.005, 0]} scale={0.151}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material} skeleton={nodes.Object_20.skeleton} />
                </group>
              </group>
              <group name="hanger_10" position={[0.015, 0.005, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.011, -0.04, -0.04]}>
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Black} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/clock.gltf')

export default Clock;