/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 coffee.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Coffee(props) {
  const { nodes, materials } = useGLTF('/coffee.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.coffee_cup.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/coffee.gltf')

export default Coffee;
