/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 degree.gltf 
Author: DrewA (https://sketchfab.com/DrewA)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diploma-frame-9030281e7df84ca8b544c2acaa3688a0
Title: Diploma Frame
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Degree(props) {
  const { nodes, materials } = useGLTF('/degree.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.242, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.pCube1_lambert1_0.geometry} material={materials.lambert1} scale={[0.663, 0.061, 0.802]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/degree.gltf')

export default Degree;