/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 lamp.gltf 
Author: KaramellGlass (https://sketchfab.com/KaramellGlass)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desk-lamp-7377ec591df04445a1aae370017aaa13
Title: Desk lamp
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Lamp(props) {
  const { nodes, materials } = useGLTF('/lamp.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.059}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-4.986, 32.561, 0]} rotation={[Math.PI, 0, 2.455]}>
            <mesh geometry={nodes['Box009_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0, 0, -0.762]} />
          </group>
          <group position={[8.672, 0.163, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Cylinder005_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
            <mesh geometry={nodes['Cylinder005_Material_#13_0'].geometry} material={materials.Material_13} />
          </group>
          <group position={[-13.343, 26.483, 0]} rotation={[-Math.PI, 0, -1.826]}>
            <mesh geometry={nodes['Object003_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0.089, 1.044, -1]} />
          </group>
          <group position={[-14.048, 26.066, 0]} rotation={[-Math.PI, 0, -1.826]}>
            <mesh geometry={nodes['Object004_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0.089, 1.044, -1]} />
          </group>
          <group position={[-14.048, 26.066, 0]} rotation={[-Math.PI, 0, -1.826]}>
            <mesh geometry={nodes['Object006_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0.089, 1.044, -1]} />
          </group>
          <group position={[-13.485, 26.557, 0]} rotation={[-Math.PI, 0, -1.826]}>
            <mesh geometry={nodes['Object008_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[0.089, 1.044, -1]} />
          </group>
          <group position={[-4.986, 32.561, 0]} rotation={[Math.PI, 0, 2.455]}>
            <mesh geometry={nodes['Object017_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[0, 0, -0.762]} />
          </group>
          <group position={[-15.811, 26.053, 0]} rotation={[Math.PI, 0, 2.455]}>
            <mesh geometry={nodes['Object018_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-12.497, -1.832, -0.762]} />
          </group>
          <group position={[-9.133, 7.291, 0]} rotation={[-Math.PI, 0, -0.678]}>
            <mesh geometry={nodes['Object019_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[-12.497, -1.832, -0.762]} />
          </group>
          <group position={[-13.485, 26.557, 0]} rotation={[-Math.PI, 0, -1.826]}>
            <mesh geometry={nodes['Object021_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[0.089, 1.044, -1]} />
          </group>
          <group position={[8.65, 29.4, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Sphere020_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
            <mesh geometry={nodes.Sphere020_Ceramic_0.geometry} material={materials.Ceramic} />
          </group>
          <mesh geometry={nodes['Cylinder001_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[-3.393, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Cylinder003_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[-7.97, 2.98, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Cylinder004_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[1.841, 36.849, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes['Cylinder006_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-3.393, 1, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Sphere001_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[-8.385, 6.918, -0.683]} rotation={[Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes['Spring013_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-4.845, 9.156, -1.754]} rotation={[0, 0, 1.85]} />
          <mesh geometry={nodes['Object012_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[-8.08, 2.392, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Object013_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[-8.124, 2.392, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Object014_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[8.672, 0.49, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Sphere017_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[5.841, 36.88, -0.667]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh geometry={nodes['Cylinder008_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[2.423, 37.547, -4.678]} rotation={[Math.PI, 0, -2.793]} />
          <mesh geometry={nodes['Object015_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[2.519, 35.883, 8.429]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes['Box010_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[1.878, 36.061, 1.639]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Object016_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[1.878, 36.061, 1.639]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Line002_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[-13.684, 28.673, 0]} rotation={[Math.PI, 0, -Math.PI]} scale={[1, 1, 1.241]} />
          <mesh geometry={nodes['Object020_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[5.841, 36.88, -0.667]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh geometry={nodes['Box011_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[19.796, 0, 4.396]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lamp.gltf')

export default Lamp;