/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 light.gltf 
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/led-ceiling-light-c20dd1e9108a418e8afa5f27d4c611bd
Title: LED Ceiling Light
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Light(props) {
  const { nodes, materials } = useGLTF('/light.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes._Ceiling_Light_metal2_0.geometry} material={materials.metal2} />
          <mesh geometry={nodes._Ceiling_Light_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes._Ceiling_Light_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes._Ceiling_Light_light_0.geometry} material={materials.light} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/light.gltf')

export default Light;