/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 notebook.gltf 
Author: KatzeSchwarz (https://sketchfab.com/katzeschwarz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/notebook-blackwhite-f3946ccc6d77475eb2e9b42e2f24ca8f
Title: Notebook (black+white)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Notebook(props) {
  const { nodes, materials } = useGLTF('/notebook.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-3.112, 0.403, -0.012]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.tex1} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/notebook.gltf')

export default Notebook;