/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 penHolder.gltf 
Author: salsikash101 (https://sketchfab.com/salsikash101)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pen-holder-a29fc7fea63c4689bf2b9b6f7b50eb44
Title: Pen Holder
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function PenHolder(props) {
  const { nodes, materials } = useGLTF('/penHolder.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={[0.762, 1, 0.762]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-0.8, 1.861, 0]} rotation={[-0.093, 0.516, 0.186]} scale={0.06}>
        <mesh geometry={nodes.Object_28.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['Material.012']} />
      </group>
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.003']} position={[0, -1.03, 0]} scale={[0.799, 0.036, 0.799]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.003']} position={[0, 1.026, 0]} scale={[0.799, 0.036, 0.799]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.005']} position={[0.533, 0.353, 0]} rotation={[0, 0, -0.197]} scale={[0.059, 1.099, 0.059]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.006']} position={[0.533, 0.353, 0]} rotation={[0, 0, -0.197]} scale={[0.059, 1.099, 0.059]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.004']} position={[0.533, 0.353, 0]} rotation={[0, 0, -0.197]} scale={[0.059, 1.099, 0.059]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Material.005']} position={[0.428, 0.353, -0.317]} rotation={[0, 0.638, -0.197]} scale={[0.059, 1.099, 0.059]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Material.006']} position={[0.428, 0.353, -0.317]} rotation={[0, 0.638, -0.197]} scale={[0.059, 1.099, 0.059]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.004']} position={[0.428, 0.353, -0.317]} rotation={[0, 0.638, -0.197]} scale={[0.059, 1.099, 0.059]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Material.008']} position={[-0.563, 0.406, 0]} rotation={[0.093, -0.516, 0.186]} scale={[0.061, 1.416, 0.061]} />
    </group>
  )
}

useGLTF.preload('/penHolder.gltf')

export default PenHolder;