/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 phone.gltf 
Author: sam_petux (https://sketchfab.com/sam_petux)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smart-phone-0d696fd16d4c4a39984a2a93993810f5
Title: Smart Phone
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

function Phone(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/phone.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Phonev2fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="������������001_1" position={[627.441, 646.204, 63.243]} rotation={[Math.PI / 2, -1.571, 0]} scale={[71.491, 33.792, 3.871]}>
                  <group name="��������������001" position={[-0.519, -0.621, 0.886]} scale={[0.024, 0.052, 0.046]}>
                    <mesh name="��������������001_Material018_0" geometry={nodes['��������������001_Material018_0'].geometry} material={materials['Material.018']} />
                    <mesh name="��������������001_Material015_0" geometry={nodes['��������������001_Material015_0'].geometry} material={materials['Material.015']} />
                    <mesh name="��������������001_Material016_0" geometry={nodes['��������������001_Material016_0'].geometry} material={materials['Material.016']} />
                  </group>
                  <group name="������������001" position={[-0.659, -0.622, 1.012]} scale={[0.054, 0.115, 0.027]}>
                    <mesh name="������������001_������������001_0" geometry={nodes['������������001_������������001_0'].geometry} material={materials['.001_12']} />
                  </group>
                  <group name="������������_����_��������������001" position={[-0.519, -0.621, 0.949]} scale={[0.024, 0.052, 0.023]}>
                    <mesh name="������������_����_��������������001_������������001_0" geometry={nodes['������������_����_��������������001_������������001_0'].geometry} material={materials['.001_12']} />
                  </group>
                  <group name="������������_����_������������001" position={[-0.658, -0.623, 0.452]} scale={[0.055, 0.118, 0.576]}>
                    <mesh name="������������_����_������������001_Material010_0" geometry={nodes['������������_����_������������001_Material010_0'].geometry} material={materials['Material.010']} />
                    <mesh name="������������_����_������������001_Material012_0" geometry={nodes['������������_����_������������001_Material012_0'].geometry} material={materials['Material.012']} />
                    <mesh name="������������_����_������������001_Material017_0" geometry={nodes['������������_����_������������001_Material017_0'].geometry} material={materials['Material.017']} />
                    <mesh name="������������_����_������������001_Material011_0" geometry={nodes['������������_����_������������001_Material011_0'].geometry} material={materials['Material.011']} />
                    <mesh name="������������_����_������������001_��������001_0" geometry={nodes['������������_����_������������001_��������001_0'].geometry} material={materials['.001_2']} />
                  </group>
                  <group name="������������������001" position={[-0.956, 0.259, 0.093]} rotation={[0, 1.571, 0]} scale={[0.565, 0.049, 0.043]}>
                    <mesh name="������������������001_������������_��������001_0" geometry={nodes['������������������001_������������_��������001_0'].geometry} material={materials['.001_1']} />
                    <mesh name="������������������001_��������001_0" geometry={nodes['������������������001_��������001_0'].geometry} material={materials['.001_2']} />
                  </group>
                  <mesh name="������������001_��������������_������������001_0" geometry={nodes['������������001_��������������_������������001_0'].geometry} material={materials['.001']} />
                  <mesh name="������������001_������������_��������001_0" geometry={nodes['������������001_������������_��������001_0'].geometry} material={materials['.001_1']} />
                  <mesh name="������������001_��������001_0" geometry={nodes['������������001_��������001_0'].geometry} material={materials['.001_2']} />
                  <mesh name="������������001_������������������001_0" geometry={nodes['������������001_������������������001_0'].geometry} material={materials['.001_3']} />
                  <mesh name="������������001_Material014_0" geometry={nodes['������������001_Material014_0'].geometry} material={materials['Material.014']} />
                  <mesh name="������������001_������������_������������001_0" geometry={nodes['������������001_������������_������������001_0'].geometry} material={materials['.001_5']} />
                  <mesh name="������������001_������������_������������001_0_1" geometry={nodes['������������001_������������_������������001_0_1'].geometry} material={materials['.001_0']} />
                  <mesh name="������������001_Material020_0" geometry={nodes['������������001_Material020_0'].geometry} material={materials['Material.020']} />
                  <mesh name="������������001_������������_������������001_0_2" geometry={nodes['������������001_������������_������������001_0_2'].geometry} material={materials['.001_1']} />
                </group>
                <group name="Cube" position={[627.794, 528.037, 62.403]} rotation={[-Math.PI / 2, 0, 0]} scale={[76.413, 76.413, 14.626]}>
                  <mesh name="Cube_Material001_0" geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube_Material002_0" geometry={nodes.Cube_Material002_0.geometry} material={materials['Material.002']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/phone.gltf')

export default Phone;