/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 plant.gltf 
Author: Giora (https://sketchfab.com/ChubbyPanda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monstera-deliciosa-potted-mid-century-plant-1ab9bf841df04c07b1819be596327629
Title: Monstera Deliciosa Potted Mid-Century plant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Plant(props) {
  const { nodes, materials } = useGLTF('/plant.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.863}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.root_HP_1_Mat2_0.geometry} material={materials['Mat.2']} position={[0.071, 0.06, 0.219]} />
          <mesh geometry={nodes.Leaves_Mat1_0.geometry} material={materials['Mat.1']} position={[4.607, 54.241, -4.895]} />
          <mesh geometry={nodes.Stand_Mat_0.geometry} material={materials.material} position={[0, 2.455, 7.585]} />
          <mesh geometry={nodes.Pot_LP_Mat_0.geometry} material={materials.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/plant.gltf')

export default Plant;