/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 shelf.gltf 
Author: Visthétique (https://sketchfab.com/bubirmelisa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/organic-wood-bookcase-a1e1b7cb1cf942449805201d150872e4
Title: Organic Wood Bookcase
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Shelf(props) {
  const { nodes, materials } = useGLTF('/shelf.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.316}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-154.544, 187.136, 17.103]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.AlarmClock_AlarmClock_0.geometry} material={materials.AlarmClock} />
            <mesh geometry={nodes.AlarmClock_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group position={[-70.526, 198.627, -10.11]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder001_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cylinder001_Orange_0.geometry} material={materials.Orange} />
          </group>
          <group position={[243.001, 64.927, 2.45]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder_WoodVeneer_0.geometry} material={materials.WoodVeneer} />
            <mesh geometry={nodes.Cylinder_VazoOutside_0.geometry} material={materials.VazoOutside} />
          </group>
          <group position={[172.852, 418.721, -12.014]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder003_Bottle2_0.geometry} material={materials.Bottle2} />
            <mesh geometry={nodes.Cylinder003_WoodVeneer_0.geometry} material={materials.WoodVeneer} />
            <mesh geometry={nodes.Cylinder003_Bottle3_0.geometry} material={materials.Bottle3} />
            <mesh geometry={nodes.Cylinder003_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Cylinder003_Bottle1_0.geometry} material={materials.Bottle1} />
          </group>
          <group position={[-172.818, 364.596, 35.842]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plant1_PolishedQuartize_0.geometry} material={materials.PolishedQuartize} />
            <mesh geometry={nodes.Plant1_Granite_Dark_Gray_0.geometry} material={materials.Granite_Dark_Gray} />
            <mesh geometry={nodes.Plant1_leaf2_smaller_clean_0.geometry} material={materials.leaf2_smaller_clean} />
            <mesh geometry={nodes.Plant1_leaf1_smaller_clean_0.geometry} material={materials.leaf1_smaller_clean} />
            <mesh geometry={nodes.Plant1__DarkGoldenrod_1_0.geometry} material={materials.DarkGoldenrod_1} />
            <mesh geometry={nodes.Plant1_Color_F18_0.geometry} material={materials.Color_F18} />
            <mesh geometry={nodes.Plant1_Leaf_Half_Top_007_0.geometry} material={materials.Leaf_Half_Top_007} />
            <mesh geometry={nodes.Plant1_Leaf_Half_Top_007_1__0.geometry} material={materials.Leaf_Half_Top_007_1} />
          </group>
          <group position={[189.06, 569.982, -2.72]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plant2_Material__3_0.geometry} material={materials.Material__3} />
            <mesh geometry={nodes.Plant2_Material__7_0.geometry} material={materials.Material__7} />
            <mesh geometry={nodes.Plant2_PolishedQuartize_0.geometry} material={materials.PolishedQuartize} />
          </group>
          <mesh geometry={nodes.Cube_Oakwood_0.geometry} material={materials.Oakwood} position={[-19.656, 327.109, -1.963]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder002_WoodVeneer_0.geometry} material={materials.WoodVeneer} position={[-148.583, 195.719, -21.67]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder007_PolishedQuartize_0.geometry} material={materials.PolishedQuartize} position={[-104.555, 546.846, -1.329]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder008_Wood2V_0.geometry} material={materials.Wood2V} position={[-224.711, 573.176, 1.634]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder009_WoodVeneer_0.geometry} material={materials.WoodVeneer} position={[-41.146, 706.77, -11.829]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shelf.gltf')

export default Shelf;