/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 speaker.gltf 
Author: Torquil Trapp (https://sketchfab.com/Planvis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bluetooth-speaker-46de470184894e2783548e9576dcb17e
Title: Bluetooth speaker
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Speaker(props) {
  const { nodes, materials } = useGLTF('/speaker.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.003, -0.003]} rotation={[-1.564, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Copper} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Grill} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Led_032Emitter} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Led_Cover} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Smooth_032Rubber} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.White_032Reflector} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.label} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.SILVER} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.SILVER} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.black_032half_032matte} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.black_032half_032matte} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.black_032half_032matte} />
      </group>
    </group>
  )
}

useGLTF.preload('/speaker.gltf')

export default Speaker;