/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 storage.gltf 
Author: holykadylo (https://sketchfab.com/holykadylo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/external-hard-drive-4k-f8de4975c0f54c1a97203c6a674f6a39
Title: External hard drive 4k
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Storage(props) {
  const { nodes, materials } = useGLTF('/storage.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['middle-texture']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/storage.gltf')

export default Storage;