/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 switch.gltf 
Author: Avot (https://sketchfab.com/avot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/light-switch-808c3de4dd874fc1b67ff15cd2645555
Title: Light Switch
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Switch(props) {
  const { nodes, materials } = useGLTF('/switch.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.CoverPlate001_lightswitch_0.geometry} material={materials.lightswitch} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.ScrewBottom001_lightswitch_0.geometry} material={materials.lightswitch} position={[0.21, -4.689, 0.01]} rotation={[-2.923, 0, 0]} scale={100} />
        <mesh geometry={nodes.ScrewTop001_lightswitch_0.geometry} material={materials.lightswitch} position={[0.21, 4.689, 0.01]} rotation={[-1.076, 0, 0]} scale={100} />
        <mesh geometry={nodes.Switch001_lightswitch_0.geometry} material={materials.lightswitch} position={[-0.25, 0.1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.SwitchHolder001_lightswitch_0.geometry} material={materials.lightswitch} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/switch.gltf')

export default Switch;