/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 tablet.gltf 
Author: Denis_Niko (https://sketchfab.com/denisniko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tablet-prop-273c413f7a5340498974b5b86b799f49
Title: Tablet prop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import Table from './Table'

function Tablet(props) {
  const { nodes, materials } = useGLTF('/tablet.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.231, 0, 0]} scale={0.047}>
        <group position={[0, 1.813, -0.12]} rotation={[0.539, Math.PI / 2, 0]} scale={0.233}>
          <mesh geometry={nodes.Object_12.geometry} material={materials.tablet} rotation={[0, -Math.PI / 2, 0]} scale={92.055} />
        </group>
        <mesh geometry={nodes.Object_5.geometry} material={materials.tablet} scale={21.471} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.tablet} position={[-3.9, 4.475, -0.025]} scale={8.425} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.screen} position={[0, -0.343, 0.008]} scale={21.471} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.tablet} position={[-3.29, 4.479, -0.025]} scale={8.425} />
      </group>
    </group>
  )
}

useGLTF.preload('/tablet.gltf')

export default Tablet;