/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 trashBin.gltf 
Author: JungleBird (https://sketchfab.com/junglebird)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trash-bin-d31d883dcef946aa884fc245bbd5a9f3
Title: Trash Bin
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function TrashBin(props) {
  const { nodes, materials } = useGLTF('/trashBin.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.trash03} scale={[0.929, 0.978, 0.929]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.trash03} position={[0, 0.02, 0]} rotation={[0, 0.942, 0]} scale={[0.025, 0.3, 0.01]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.trash03} position={[0, -0.257, 0]} scale={[0.206, 0.219, 0.206]} />
    </group>
  )
}

useGLTF.preload('/trashBin.gltf')

export default TrashBin;